THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1579022036608/work/aten/src/THC/THCGeneral.cpp line=50 error=38 : no CUDA-capable device is detected
Traceback (most recent call last):
  File "main.py", line 341, in <module>
    main()
  File "main.py", line 84, in main
    model.cuda()
  File "/opt/anaconda3/envs/dc_p27/lib/python2.7/site-packages/torch/nn/modules/module.py", line 304, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/opt/anaconda3/envs/dc_p27/lib/python2.7/site-packages/torch/nn/modules/module.py", line 201, in _apply
    module._apply(fn)
  File "/opt/anaconda3/envs/dc_p27/lib/python2.7/site-packages/torch/nn/modules/module.py", line 201, in _apply
    module._apply(fn)
  File "/opt/anaconda3/envs/dc_p27/lib/python2.7/site-packages/torch/nn/modules/module.py", line 201, in _apply
    module._apply(fn)
  File "/opt/anaconda3/envs/dc_p27/lib/python2.7/site-packages/torch/nn/modules/module.py", line 223, in _apply
    param_applied = fn(param)
  File "/opt/anaconda3/envs/dc_p27/lib/python2.7/site-packages/torch/nn/modules/module.py", line 304, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/opt/anaconda3/envs/dc_p27/lib/python2.7/site-packages/torch/cuda/__init__.py", line 197, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected at /opt/conda/conda-bld/pytorch_1579022036608/work/aten/src/THC/THCGeneral.cpp:50
